{{- if .Values.rbac.create }}
# kubernetes_plugin: Give access to pods endpoint
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}:logstream-workergroup
  labels:
    {{- include "logstream-workergroup.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
{{- end }}
