apiVersion: v1
kind: Secret
type: Opaque
metadata: 
 name: logstream-config-{{ include "logstream-workergroup.fullname" . }}
stringData:
  url-master: "tcp://{{ .Values.config.token }}@{{ .Values.config.host }}:4200?group={{ .Values.config.tag }}&tag={{ .Values.config.tag }}"
