apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstream-workergroup.fullname" . }}
  labels:
    {{- include "logstream-workergroup.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations  | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
      {{-  range .Values.service.ports }}
      - port: {{ .port }}
        targetPort: {{ .port }}
        protocol: {{ .protocol }}
        name: {{ .name }}
      {{- end }}
  selector:
    {{- include "logstream-workergroup.selectorLabels" . | nindent 4 }}
