version: '3.5'
services:
  gogen-filebeat:
    build:
      context: gogen-filebeat
    volumes:
    #  - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
    #  - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/snap/docker/common/var-lib-docker:/var/lib/docker/containers"
      - "/run/docker.sock:/var/run/docker.sock"
  cribl:
    image: cribl/cribl:latest
    ports:
      - "10080:10080"
      - "10001:10001"
      - "9000:9000"
    volumes:
      - "./cribl:/opt/cribl/local/cribl"
  splunk:
    image: cribl/splunk:latest
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
      - "9997:9997"
    environment:
      - "DONT_TIMEOUT=1"
      - "CRIBL_ROUTING_DEMO=1"

