---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apiserver
    spec:
      containers:
        - env:
            - name: DISABLE_ACCESS_COUNT
              value: "1"
          image: apiserver
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl --fail -s http://localhost:4000/ || exit 1
            failureThreshold: 3
            periodSeconds: 15
            timeoutSeconds: 10
          name: apiserver
          ports:
            - containerPort: 4000
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: apiserver
  name: apiserver
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: apiserver
status:
  loadBalancer: {}