sources:
  - training
  # - gogen-businessevent-hec
  # - gogen-accesscombined-forwarder
  # - gogen-authfailed-filebeat
  # - gogen-statechange-syslog
  - gogen-bigjson-kafka
  - splunk
destination: ../.run