sources:
  - training
  # - gogen-businessevent-hec
  - gogen-accesscombined-forwarder
  # - gogen-authfailed-filebeat
  # - gogen-statechange-syslog
  # - gogen-bigjson-kafka
  # - gogen-metrics-dogstatsd
  # - splunk
  - enrich
  - metrics
  - elasticsearch
destination: ../.run
mergeconfig:
  - pattern: route.yml$
    opts:
      arrayMerge: prepend
      op: mergeYaml
replaceconfig:
  - pattern: /cribl/master/groups/default/local/cribl
    filePathReplace: /cribl/cribl
  - pattern: /cribl/master/groups/metrics/local/cribl
    filePathReplace: /cribl/cribl
  - pattern: /cribl/master/groups/default/data
    filePathReplace: /cribl/data