version: '3.5'
services:
  cribl:
    build:
      context: cribl
    ports:
      - "9000:9000"
    volumes:
      - "./cribl/master/groups:/opt/cribl/groups"
      - "./cribl/master/local:/opt/cribl/local"
      - "./cribl/scripts:/opt/cribl/scripts"
    environment:
      - SCOPE_OUT_DEST=udp://${CRIBL_STATSD}
  cribl-w0:
    build:
      context: cribl
    ports:
      - "9002:9000"
      - "10200:10200"
      - "10088:10088"
      - "10080:10080"
      - "10001:10001"
      - "9999:9999"
      - "5140:5140"
    environment:
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl:4200
      - SCOPE_OUT_DEST=udp://${CRIBL_STATSD}
  cribl-w1:
    build:
      context: cribl
    ports:
      - "9003:9000"
      - "8125:8125"
      - "8125:8125/udp"
    environment:
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl:4200?tag=metrics
      - SCOPE_OUT_DEST=udp://${CRIBL_STATSD}
