---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cribl
  name: cribl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cribl
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cribl
    spec:
      containers:
        - env:
            - name: CRIBL_AFTER_START_CMD_1
              value: sleep 60 && $CRIBL_HOME/scripts/cli-deploy > /tmp/deploy.log
            - name: CRIBL_HOME
              value: /opt/cribl
          image: cribl-master
          name: cribl
          ports:
            - containerPort: 9000
            - containerPort: 4200
          resources: 
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 750m
              memory: 1024Mi

      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cribl
  name: cribl
spec:
  ports:
    - name: "api"
      port: 9000
      targetPort: 9000
    - name: "worker"
      port: 4200
      targetPort: 4200
  selector:
    io.kompose.service: cribl
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cribl-w0
  name: cribl-w0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cribl-w0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cribl-w0
    spec:
      containers:
        - env:
            - name: CRIBL_DIST_MASTER_URL
              value: tcp://criblmaster@cribl:4200?tag=logs
          image: cribl/cribl:next
          name: cribl-w0
          ports:
            - containerPort: 9000
            - containerPort: 10200
            - containerPort: 10088
            - containerPort: 10080
            - containerPort: 10001
            - containerPort: 9999
            - containerPort: 3514
            - containerPort: 5140
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cribl-w0
  name: cribl-w0
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9000
    - name: "10200"
      port: 10200
      targetPort: 10200
    - name: "10088"
      port: 10088
      targetPort: 10088
    - name: "10080"
      port: 10080
      targetPort: 10080
    - name: "10001"
      port: 10001
      targetPort: 10001
    - name: "9999"
      port: 9999
      targetPort: 9999
    - name: "3514"
      port: 3514
      targetPort: 3514
    - name: "5140"
      port: 5140
      targetPort: 5140
  selector:
    io.kompose.service: cribl-w0
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cribl-w1
  name: cribl-w1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cribl-w1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cribl-w1
    spec:
      containers:
        - env:
            - name: CRIBL_AFTER_START_CMD_1
              value: apt-get update && apt-get install -y --no-install-recommends mtr python python-pip
            - name: CRIBL_AFTER_START_CMD_2
              value: pip install speedtest-cli
            - name: CRIBL_DIST_MASTER_URL
              value: tcp://criblmaster@cribl:4200?tag=metrics
          image: cribl/cribl:next
          name: cribl-w1
          ports:
            - containerPort: 9000
            - containerPort: 8125
            - containerPort: 8125
              protocol: UDP
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cribl-w1
  name: cribl-w1
spec:
  ports:
    - name: "9003"
      port: 9003
      targetPort: 9000
    - name: "8125"
      port: 8125
      targetPort: 8125
    - name: 8125-udp
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    io.kompose.service: cribl-w1
status:
  loadBalancer: {}
