apiVersion: v1
kind: Pod
metadata:
  name: demo
  annotations:
    appscope.cribl.io/inject: 'true'
spec:
  # initContainers:
  #   - name: appscope-init
  #     image: cribl/appscope-init:0.0.0
  #     volumeMounts:
  #       - mountPath: /scope
  #         name: scope
  containers:
    - name: scopedemo
      image: ubuntu:18.04
      command: ["/bin/sleep", "infinity"]
      imagePullPolicy: IfNotPresent
  #     volumeMounts:
  #       - mountPath: /scope
  #         name: scope
  #     env:
  #       - name: LD_PRELOAD
  #         value: /scope/libscope.so
  #       - name: SCOPE_CONF_PATH
  #         value: /scope/scope.yml
  # volumes:
  #   - emptyDir: {}
  #     name: scope
