---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: WEBHOOK_APP
  labels:
    app: WEBHOOK_APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WEBHOOK_APP
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: WEBHOOK_APP
    spec:
      containers:
        - name: WEBHOOK_APP
          image: DOCKER_REPO_NAME/WEBHOOK_APP:0.0.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: certs
              mountPath: /etc/certs
              readOnly: true
          ports:
            - containerPort: 4443
              protocol: TCP
      volumes:
        - name: certs
          secret:
            secretName: WEBHOOK_APP-tls-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: WEBHOOK_APP
spec:
  type: ClusterIP
  ports:
    - name: 4443-tcp
      protocol: TCP
      port: 443
      targetPort: 4443
  selector:
    app: WEBHOOK_APP 
