version: '3.5'
services:
  apiserver:
    environment:
      - DISABLE_ACCESS_COUNT=0
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
