---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.config.scName }}
  storageClassName:   {{ .Values.config.scName }}
  {{- end}}
  resources:
    requests:
      storage: 10Gi
