version: '3.5'
services:
  minio:
    image: minio/minio:latest
    environment:
      - "MINIO_ACCESS_KEY=ACCESSKEY"
      - "MINIO_SECRET_KEY=SECRETKEY"
    ports:
      - "9001:9000"
    volumes:
      - "./minio:/data"
    command: server /data

